# -*- coding: utf-8 -*-
"""
Sentiment Words and Modifiers Definition
Contains sentiment words, modifiers for Vietnamese and English
Includes music-specific vocabulary
"""

# ===========================
# VIETNAMESE SENTIMENT WORDS
# ===========================

VI_POSITIVE_WORDS = {
    # Positive emotions and feelings
    'xinh': 1,
    'đỉnh': 1,
    "phê": 1,
    'tuyệt vời': 1,
    'tuyệt': 1,
    'xuất sắc': 1,
    'tốt': 1,
    'tốt lắm': 1,
    'hay': 1,
    'hay ho': 1,
    'đẹp': 1,
    'đẹp lắm': 1,
    'đẹp tuyệt': 1,
    'lớn': 1,
    'vĩ đại': 1,
    'tuyệt đệp': 1,
    'thiệu': 1,
    'yêu': 1,
    'yêu thích': 1,
    'thích': 1,
    'thích lắm': 1,
    'ghiền': 1,
    'mê': 1,
    'cuồng': 1,
    'bình an': 1,
    'vui': 1,
    'vui vẻ': 1,
    'vui tươi': 1,
    'hạnh phúc': 1,
    'rất hạnh phúc': 1,
    'hài lòng': 1,
    'thỏa mãn': 1,
    'thoải mái': 1,
    'dễ chịu': 1,
    'khoái': 1,
    'tuyệt khoái': 1,
    'thích thú': 1,
    'vui lây': 1,
    'tươi sáng': 1,
    'sáng sủa': 1,
    'kì diệu': 1,
    'tuyệt diệu': 1,
    'công dụng': 1,
    'hiệu quả': 1,
    'rạng riêng': 1,
    'vinh quang': 1,
    'huy hoàng': 1,
    'linh hoạt': 1,
    'nhanh': 1,
    'nhanh chóng': 1,
    'thông minh': 1,
    'khôn ngoan': 1,
    'tài ba': 1,
    'tài giỏi': 1,
    'giỏi': 1,
    'lợi': 1,
    'nổi tiếng': 1,
    'có lợi': 1,
    'tốt lành': 1,
    'tốt đẹp': 1,
    'mau lẹ': 1,
    'chắc chắn': 1,
    'tin tưởng': 1,
    'an tâm': 1,
    'bình yên': 1,
    'thương': 1,
    'hiền từ': 1,
    'nhân từ': 1,
    'tử tế': 1,
    'lạc quan': 1,
    'hoài bão': 1,
    'dũng cảm': 1,
    'can đảm': 1,
    'mạnh mẽ': 1,
    'anh hùng': 1,
    'cao quý': 1,
    'tôn trọng': 1,
    'trân trọng': 1,
    'quý báu': 1,
    'có giá trị': 1,
    
    # Music-specific positive words
    'nghiện' : 1,
    'đã tai' : 1,
    'nhạc hay': 1,
    'nhạc đẹp': 1,
    'nhạc tuyệt': 1,
    'giai điệu tuyệt vời': 1,
    'giai điệu đẹp': 1,
    'âm nhạc hay': 1,
    'âm nhạc tuyệt vời': 1,
    'giọng hay': 1,
    'giọng đẹp': 1,
    'giọng tuyệt': 1,
    'hát hay': 1,
    'hát tuyệt': 1,
    'hát đẹp': 1,
    'ca sĩ hay': 1,
    'ca sĩ tuyệt': 1,
    'ca sĩ giỏi': 1,
    'bản nhạc hay': 1,
    'bản nhạc tuyệt': 1,
    'beat hay': 1,
    'beat tuyệt': 1,
    'sản xuất tốt': 1,
    'thu âm tốt': 1,
    'mixing tốt': 1,
    'masterin tốt': 1,
    'harmonia tốt': 1,
    'điệu tuyệt': 1,
    'lời hay': 1,
    'lời tuyệt': 1,
    'sáng tác hay': 1,
    'arrangement tốt': 1,
    'âm thanh tinh': 1,
    'âm thanh rõ': 1,
    'tiếng tuyệt': 1,
    'âm lượng cân bằng': 1,
    'nhạc remix hay': 1,
    'phối hợp tốt': 1,
    'dàn nhạc tuyệt': 1,
    'ca khúc hay': 1,
    'bài hát hay': 1,
    'bài hát tuyệt': 1,
    'alb tốt': 1,
    'ep hay': 1,
    'single hay': 1,
    'playlist hay': 1,
    'hòa âm tốt': 1,
    'kết hợp tốt': 1,
    'phối lời tốt': 1,
    'tác phẩm tuyệt': 1,
    'sáng tác tuyệt': 1,
    'ca dao hay': 1,
    'nhạc vui': 1,
    'vui vẻ': 1,
    'nhẹ nhàng': 1,
    'sâu sắc': 1,
    'ý nghĩa': 1,
    'cảm động': 1,
    'xúc động': 1,
}

VI_NEGATIVE_WORDS = {
    # Negative emotions and feelings
    'dở': -1,
    'tệ': -1,
    'tệ hại': -1,
    'kinh khủng': -1,
    'khủng khiếp': -1,
    'ghê tởm': -1,
    'gớm ghiếc': -1,
    'bệnh hoạn': -1,
    'ghê': -1,
    'đểu': -1,
    'tồi': -1,
    'tồi tệ': -1,
    'xấu': -1,
    'xấu xa': -1,
    'xấu lạ': -1,
    'lộn xộn': -1,
    'bẩn': -1,
    'bẩn thỉu': -1,
    'bủn rủn': -1,
    'bê bối': -1,
    'xấu hổ': -1,
    'đáng thẹn': -1,
    'đáng nhục': -1,
    'nhục': -1,
    'phẫn nộ': -1,
    'giận': -1,
    'giận dữ': -1,
    'tức giận': -1,
    'nổi cơn giận': -1,
    'tức': -1,
    'buồn': -1,
    'buồn bã': -1,
    'buồn rầu': -1,
    'chán': -1,
    'chán chường': -1,
    'chán nản': -1,
    'nản lòng': -1,
    'thất vọng': -1,
    'thất vọng lớn': -1,
    'tuyệt vọng': -1,
    'mất hy vọng': -1,
    'đau buồn': -1,
    'đau khổ': -1,
    'khổ sở': -1,
    'thống khổ': -1,
    'sợ': -1,
    'sợ hãi': -1,
    'kinh hãi': -1,
    'hoảng hốt': -1,
    'hoảng sợ': -1,
    'sợ chết': -1,
    'ghét': -1,
    'ghét cay đắng': -1,
    'ghét bỏ': -1,
    'chán ghét': -1,
    'không thích': -1,
    'không ưa': -1,
    'không yêu': -1,
    'chán': -1,
    'khiếp': -1,
    'khiếp sợ': -1,
    'lo lắng': -1,
    'lo sợ': -1,
    'lo ngại': -1,
    'băn khoăn': -1,
    'rối loạn': -1,
    'hỗn loạn': -1,
    'bộn bề': -1,
    'nặng nề': -1,
    'ngặc ngạnh': -1,
    'cay hot': -1,
    'tự mãn': -1,
    'nông cạn': -1,
    'hẹp hòi': -1,
    'tham lam': -1,
    'tham': -1,
    'lập lòe': -1,
    'dối trá': -1,
    'nói dối': -1,
    'giả dối': -1,
    'phản bội': -1,
    'tệ thảm': -1,
    'tan nát': -1,
    'vỡ tan': -1,
    'sụp đổ': -1,
    'thất bại': -1,
    'thua': -1,
    'thua kém': -1,
    'kém': -1,
    'dốn': -1,
    'ngu dốn': -1,
    'ngu ngốc': -1,
    'ngu': -1,
    'mất cơ hội': -1,
    'lỏng lẻo': -1,
    'thiếu': -1,
    'thiếu hụt': -1,
    'béo': -1,
    'mập': -1,
    'gầy': -1,
    'gầy guộc': -1,
    'xơ xác': -1,
    'ốm': -1,
    'ốm yếu': -1,
    'yếu': -1,
    'yếu ớt': -1,
    'suy yếu': -1,
    'suy sụp': -1,
    'cồng kềnh': -1,
    'nặng': -1,
    'nặng nợ': -1,
    'nặng lỗi': -1,
    'quá tải': -1,
    'tội': -1,
    'tội lỗi': -1,
    'tội ác': -1,
    'quỷ': -1,
    'quỷ quyệt': -1,
    'hung ác': -1,
    'man rợ': -1,
    'tàn bạo': -1,
    'độc ác': -1,
    'ác': -1,
    'ác độc': -1,
    'chán cá': -1,
    'chán chệ': -1,
    'chán nã': -1,
    
    # Music-specific negative words
    'đau tai': -1,
    'tệ': -1,
    'xấu': -1,
    'kém': -1,
    'nhạc buồn': -1,
    'tồi': -1,
    'giai điệu xấu': -1,
    'giai điệu tồi': -1,
    'giai điệu kém': -1,
    'âm nhạc tệ': -1,
    'âm nhạc xấu': -1,
    'âm nhạc kém': -1,
    'giọng xấu': -1,
    'giọng kém': -1,
    'giọng tệ': -1,
    'hát xấu': -1,
    'hát kém': -1,
    'hát tệ': -1,
    'ca sĩ xấu': -1,
    'ca sĩ kém': -1,
    'ca sĩ tệ': -1,
    'bản nhạc xấu': -1,
    'bản nhạc tệ': -1,
    'bản nhạc kém': -1,
    'beat xấu': -1,
    'beat kém': -1,
    'beat tệ': -1,
    'sản xuất tệ': -1,
    'sản xuất xấu': -1,
    'thu âm tệ': -1,
    'thu âm xấu': -1,
    'mixing tệ': -1,
    'mixing xấu': -1,
    'mastering tệ': -1,
    'mastering xấu': -1,
    'harmonia tệ': -1,
    'harmonia xấu': -1,
    'lời xấu': -1,
    'lời kém': -1,
    'lời tệ': -1,
    'sáng tác tệ': -1,
    'sáng tác xấu': -1,
    'sáng tác kém': -1,
    'arrangement tệ': -1,
    'arrangement xấu': -1,
    'arrangement kém': -1,
    'âm thanh tệ': -1,
    'âm thanh xấu': -1,
    'âm thanh kém': -1,
    'âm thanh nhiễu': -1,
    'tiếng xấu': -1,
    'tiếng kém': -1,
    'nhạc remix tệ': -1,
    'nhạc remix xấu': -1,
    'dàn nhạc tệ': -1,
    'dàn nhạc xấu': -1,
    'ca khúc tệ': -1,
    'ca khúc xấu': -1,
    'bài hát tệ': -1,
    'bài hát xấu': -1,
    'bài hát kém': -1,
    'alb tệ': -1,
    'alb xấu': -1,
    'ep tệ': -1,
    'ep xấu': -1,
    'single tệ': -1,
    'single xấu': -1,
    'playlist tệ': -1,
    'playlist xấu': -1,
    'hòa âm tệ': -1,
    'hòa âm xấu': -1,
    'kết hợp tệ': -1,
    'kết hợp xấu': -1,
    'phối lời tệ': -1,
    'phối lời xấu': -1,
    'tác phẩm tệ': -1,
    'tác phẩm xấu': -1,
    'sáng tác tệ': -1,
    'tạp âm': -1,
    'nhiễu âm': -1,
    'bị cắt': -1,
    'bị méo': -1,
    'bị méo tiếng': -1,
    'chất lượng thấp': -1,
    'chất lượng kém': -1,
    'không cân bằng': -1,
    'mất điều': -1,
    'không điều': -1,
}

VI_SENTIMENT_WORDS = {**VI_POSITIVE_WORDS, **VI_NEGATIVE_WORDS}

# ===========================
# ENGLISH SENTIMENT WORDS
# ===========================

EN_POSITIVE_WORDS = {
    # Positive adjectives and verbs
    'excellent': 1,
    'amazing': 1,
    'wonderful': 1,
    'fantastic': 1,
    'great': 1,
    'good': 1,
    'beautiful': 1,
    'lovely': 1,
    'gorgeous': 1,
    'stunning': 1,
    'awesome': 1,
    'brilliant': 1,
    'perfect': 1,
    'superb': 1,
    'outstanding': 1,
    'exceptional': 1,
    'fabulous': 1,
    'magnificent': 1,
    'splendid': 1,
    'marvelous': 1,
    'marvellous': 1,
    'impressive': 1,
    'love': 1,
    'loves': 1,
    'loved': 1,
    'loving': 1,
    'like': 1,
    'likes': 1,
    'liked': 1,
    'liking': 1,
    'enjoy': 1,
    'enjoys': 1,
    'enjoyed': 1,
    'enjoying': 1,
    'happy': 1,
    'happily': 1,
    'happiness': 1,
    'pleased': 1,
    'pleasure': 1,
    'delighted': 1,
    'delight': 1,
    'joyful': 1,
    'joy': 1,
    'glad': 1,
    'gladly': 1,
    'smile': 1,
    'smiling': 1,
    'laughing': 1,
    'laugh': 1,
    'fun': 1,
    'funny': 1,
    'hilarious': 1,
    'bright': 1,
    'cheerful': 1,
    'cheerfully': 1,
    'cheer': 1,
    'positive': 1,
    'optimistic': 1,
    'hope': 1,
    'hopeful': 1,
    'hoped': 1,
    'confident': 1,
    'confidence': 1,
    'trust': 1,
    'trustworthy': 1,
    'trusting': 1,
    'smart': 1,
    'clever': 1,
    'intelligent': 1,
    'quick': 1,
    'fast': 1,
    'sharp': 1,
    'strong': 1,
    'strength': 1,
    'powerful': 1,
    'power': 1,
    'capable': 1,
    'ability': 1,
    'able': 1,
    'skilled': 1,
    'skill': 1,
    'talented': 1,
    'talent': 1,
    'pure': 1,
    'clean': 1,
    'cleanliness': 1,
    'fresh': 1,
    'peaceful': 1,
    'peace': 1,
    'calm': 1,
    'calmly': 1,
    'kind': 1,
    'kindness': 1,
    'kindly': 1,
    'gentle': 1,
    'nice': 1,
    'friendly': 1,
    'friend': 1,
    'care': 1,
    'caring': 1,
    'sweet': 1,
    'helpful': 1,
    'help': 1,
    'hero': 1,
    'heroic': 1,
    'brave': 1,
    'bravery': 1,
    'courage': 1,
    'courageous': 1,
    'honest': 1,
    'honesty': 1,
    'truthful': 1,
    'truth': 1,
    'sincere': 1,
    'sincerely': 1,
    'fair': 1,
    'justice': 1,
    'just': 1,
    'right': 1,
    'righteous': 1,
    'moral': 1,
    'virtue': 1,
    'virtuous': 1,
    'honor': 1,
    'humble': 1,
    'humility': 1,
    'glory': 1,
    'glorious': 1,
    'success': 1,
    'successful': 1,
    'win': 1,
    'winner': 1,
    'victory': 1,
    'triumph': 1,
    'goodness': 1,
    'worthy': 1,
    'value': 1,
    'valuable': 1,
    'rich': 1,
    'wealth': 1,
    'lucky': 1,
    'luck': 1,
    'fortunate': 1,
    'blessing': 1,
    'blessed': 1,
    'benefit': 1,
    'beneficial': 1,
    'useful': 1,
    'use': 1,
    'smooth': 1,
    'easy': 1,
    'easily': 1,
    'simple': 1,
    'simply': 1,
    
    # Music-specific positive words
    'great music': 1,
    'great song': 1,
    'great artist': 1,
    'good music': 1,
    'good song': 1,
    'beautiful music': 1,
    'beautiful melody': 1,
    'beautiful voice': 1,
    'amazing voice': 1,
    'amazing song': 1,
    'wonderful music': 1,
    'wonderful song': 1,
    'wonderful voice': 1,
    'excellent music': 1,
    'excellent song': 1,
    'excellent voice': 1,
    'love this song': 1,
    'love this music': 1,
    'love this artist': 1,
    'love it': 1,
    'awesome song': 1,
    'awesome music': 1,
    'awesome artist': 1,
    'brilliant melody': 1,
    'brilliant arrangement': 1,
    'brilliant performance': 1,
    'perfect production': 1,
    'perfect mix': 1,
    'perfect mastering': 1,
    'outstanding performance': 1,
    'outstanding vocals': 1,
    'exceptional talent': 1,
    'exceptional artist': 1,
    'fabulous voice': 1,
    'magnificent performance': 1,
    'splendid music': 1,
    'splendid performance': 1,
    'marvelous voice': 1,
    'impressive voice': 1,
    'impressive performance': 1,
    'enjoyed': 1,
    'enjoy': 1,
    'enjoying': 1,
    'happy': 1,
    'pleased': 1,
    'delighted': 1,
    'catchy': 1,
    'catchy tune': 1,
    'catchy melody': 1,
    'smooth': 1,
    'smooth vocals': 1,
    'clear vocals': 1,
    'clear sound': 1,
    'crisp': 1,
    'crisp sound': 1,
    'clean production': 1,
    'powerful vocals': 1,
    'powerful performance': 1,
    'energetic': 1,
    'energetic performance': 1,
    'emotional': 1,
    'emotional song': 1,
    'emotional performance': 1,
    'touching': 1,
    'touching song': 1,
    'inspiring': 1,
    'inspiring song': 1,
    'uplifting': 1,
    'uplifting music': 1,
    'feels': 1,
    'vibe': 1,
    'good vibe': 1,
    'great vibe': 1,
    'beat': 1,
    'good beat': 1,
    'great beat': 1,
    'sick beat': 1,
    'dope': 1,
    'fire': 1,
    'lit': 1,
    'banger': 1,
    'hit': 1,
    'classic': 1,
    'classics': 1,
    'iconic': 1,
    'legendary': 1,
    'timeless': 1,
}

EN_NEGATIVE_WORDS = {
    # Negative adjectives and verbs
    'bad': -1,
    'badly': -1,
    'worse': -1,
    'worst': -1,
    'terrible': -1,
    'terribly': -1,
    'horrible': -1,
    'horrid': -1,
    'awful': -1,
    'awfully': -1,
    'dreadful': -1,
    'dreadfully': -1,
    'hideous': -1,
    'ugly': -1,
    'disgusting': -1,
    'disgust': -1,
    'nasty': -1,
    'vile': -1,
    'foul': -1,
    'rotten': -1,
    'poor': -1,
    'poorly': -1,
    'inadequate': -1,
    'fail': -1,
    'failure': -1,
    'failed': -1,
    'lose': -1,
    'lost': -1,
    'loss': -1,
    'loser': -1,
    'defeat': -1,
    'defeated': -1,
    'sad': -1,
    'sadly': -1,
    'sadness': -1,
    'unhappy': -1,
    'unhappily': -1,
    'miserable': -1,
    'miserably': -1,
    'misery': -1,
    'depressed': -1,
    'depression': -1,
    'depressing': -1,
    'gloomy': -1,
    'gloom': -1,
    'dark': -1,
    'darkness': -1,
    'grief': -1,
    'grieved': -1,
    'sorrowful': -1,
    'sorry': -1,
    'sorrow': -1,
    'crying': -1,
    'cry': -1,
    'tears': -1,
    'tear': -1,
    'hate': -1,
    'hated': -1,
    'hateful': -1,
    'hating': -1,
    'hates': -1,
    'dislike': -1,
    'dislikes': -1,
    'disliked': -1,
    'disliking': -1,
    'angry': -1,
    'anger': -1,
    'angrily': -1,
    'rage': -1,
    'raging': -1,
    'furious': -1,
    'furiously': -1,
    'fury': -1,
    'annoyed': -1,
    'annoying': -1,
    'annoy': -1,
    'irritated': -1,
    'irritating': -1,
    'irritate': -1,
    'frustrated': -1,
    'frustration': -1,
    'frustrating': -1,
    'painful': -1,
    'pain': -1,
    'ache': -1,
    'aching': -1,
    'hurt': -1,
    'hurting': -1,
    'suffer': -1,
    'suffering': -1,
    'torture': -1,
    'tormented': -1,
    'agony': -1,
    'agonizing': -1,
    'sick': -1,
    'sickness': -1,
    'ill': -1,
    'illness': -1,
    'disease': -1,
    'diseased': -1,
    'weak': -1,
    'weakness': -1,
    'weaken': -1,
    'tired': -1,
    'exhausted': -1,
    'exhaustion': -1,
    'exhausting': -1,
    'boring': -1,
    'bore': -1,
    'bored': -1,
    'boredom': -1,
    'dull': -1,
    'tedious': -1,
    'tediously': -1,
    'monotonous': -1,
    'monotony': -1,
    'fear': -1,
    'feared': -1,
    'fearful': -1,
    'fearing': -1,
    'fears': -1,
    'afraid': -1,
    'scary': -1,
    'scared': -1,
    'scare': -1,
    'frightened': -1,
    'frightening': -1,
    'frighten': -1,
    'terror': -1,
    'terrified': -1,
    'terrify': -1,
    'horrify': -1,
    'horrified': -1,
    'horrifying': -1,
    'dread': -1,
    'dreaded': -1,
    'doubt': -1,
    'doubting': -1,
    'doubtful': -1,
    'doubts': -1,
    'uncertain': -1,
    'uncertainty': -1,
    'unsure': -1,
    'insecure': -1,
    'insecurity': -1,
    'worried': -1,
    'worry': -1,
    'worrying': -1,
    'anxious': -1,
    'anxiety': -1,
    'anxiously': -1,
    'nervous': -1,
    'nervously': -1,
    'nervousness': -1,
    'uncomfortable': -1,
    'embarrassed': -1,
    'embarrassment': -1,
    'embarrassing': -1,
    'embarrass': -1,
    'ashamed': -1,
    'shame': -1,
    'shameful': -1,
    'shamefully': -1,
    'guilty': -1,
    'guilt': -1,
    'regret': -1,
    'regretful': -1,
    'regretting': -1,
    'regrets': -1,
    'disappointed': -1,
    'disappointment': -1,
    'disappointing': -1,
    'disappoint': -1,
    'unfair': -1,
    'injustice': -1,
    'unjust': -1,
    'unjustly': -1,
    'wrong': -1,
    'wrongly': -1,
    'evil': -1,
    'evilly': -1,
    'wicked': -1,
    'wickedly': -1,
    'wickedness': -1,
    'cruel': -1,
    'cruelly': -1,
    'cruelty': -1,
    'brutal': -1,
    'brutally': -1,
    'brutality': -1,
    'violence': -1,
    'violent': -1,
    'violently': -1,
    'dirty': -1,
    'dirtiness': -1,
    'filthy': -1,
    'filth': -1,
    'unclean': -1,
    'contaminated': -1,
    'contamination': -1,
    'contaminate': -1,
    'poison': -1,
    'poisoned': -1,
    'poisoning': -1,
    'toxic': -1,
    'toxin': -1,
    'hazard': -1,
    'hazardous': -1,
    'danger': -1,
    'dangerous': -1,
    'dangerously': -1,
    'risk': -1,
    'risky': -1,
    'riskily': -1,
    'threat': -1,
    'threatening': -1,
    'threaten': -1,
    'threatened': -1,
    'hostile': -1,
    'hostility': -1,
    'enemy': -1,
    'enmity': -1,
    'conflict': -1,
    'conflicting': -1,
    'argue': -1,
    'argument': -1,
    'arguing': -1,
    'fight': -1,
    'fighting': -1,
    'fought': -1,
    'battle': -1,
    'battling': -1,
    'war': -1,
    'warfare': -1,
    'dishonest': -1,
    'dishonestly': -1,
    'dishonesty': -1,
    'cheat': -1,
    'cheating': -1,
    'cheater': -1,
    'cheated': -1,
    'deceive': -1,
    'deceived': -1,
    'deceiving': -1,
    'deception': -1,
    'deceiver': -1,
    'false': -1,
    'falsity': -1,
    'falsely': -1,
    'fake': -1,
    'faking': -1,
    'faked': -1,
    'lie': -1,
    'lied': -1,
    'lying': -1,
    'liar': -1,
    'betray': -1,
    'betrayed': -1,
    'betraying': -1,
    'betrayal': -1,
    'traitor': -1,
    'treachery': -1,
    'treacherous': -1,
    'stab': -1,
    'stabbed': -1,
    'stabbing': -1,
    'ignorant': -1,
    'ignorance': -1,
    'stupid': -1,
    'stupidity': -1,
    'dumb': -1,
    'dumbness': -1,
    'idiot': -1,
    'idiotic': -1,
    'fool': -1,
    'foolish': -1,
    'foolishness': -1,
    'silly': -1,
    'silliness': -1,
    'absurd': -1,
    'absurdly': -1,
    'absurdity': -1,
    'ridiculous': -1,
    'ridiculously': -1,
    'ridicule': -1,
    'laughable': -1,
    'mockery': -1,
    'mock': -1,
    'mocked': -1,
    'mocking': -1,
    'mockingly': -1,
    'ugliness': -1,
    'deformed': -1,
    'deformity': -1,
    'scarred': -1,
    'scar': -1,
    'handicap': -1,
    'handicapped': -1,
    'crippled': -1,
    'cripple': -1,
    'disabled': -1,
    'disability': -1,
    'defect': -1,
    'defective': -1,
    'flawed': -1,
    'flaw': -1,
    'imperfect': -1,
    'imperfection': -1,
    'incomplete': -1,
    'incompleteness': -1,
    'broken': -1,
    'break': -1,
    'broke': -1,
    'damaged': -1,
    'damage': -1,
    'damaging': -1,
    'ruin': -1,
    'ruined': -1,
    'ruinous': -1,
    'ruination': -1,
    'destroyed': -1,
    'destroy': -1,
    'destroying': -1,
    'destruction': -1,
    'destructive': -1,
    
    # Music-specific negative words
    'bad music': -1,
    'bad song': -1,
    'bad voice': -1,
    'bad artist': -1,
    'terrible music': -1,
    'terrible song': -1,
    'terrible voice': -1,
    'awful music': -1,
    'awful song': -1,
    'awful voice': -1,
    'horrible music': -1,
    'horrible song': -1,
    'horrible voice': -1,
    'poor quality': -1,
    'poor production': -1,
    'poor mix': -1,
    'weak vocals': -1,
    'weak performance': -1,
    'weak voice': -1,
    'out of tune': -1,
    'off key': -1,
    'out of rhythm': -1,
    'off beat': -1,
    'pitchy': -1,
    'nasal': -1,
    'nasally': -1,
    'harsh': -1,
    'harsh vocals': -1,
    'harsh tone': -1,
    'straining': -1,
    'strained voice': -1,
    'strained vocals': -1,
    'auto tune': -1,
    'too much autotune': -1,
    'cheap sound': -1,
    'cheap production': -1,
    'low quality': -1,
    'low quality production': -1,
    'muffled': -1,
    'muffled sound': -1,
    'muffled vocals': -1,
    'muddy': -1,
    'muddy mix': -1,
    'muddy sound': -1,
    'distorted': -1,
    'distorted vocals': -1,
    'distorted sound': -1,
    'harsh': -1,
    'sharp': -1,
    'shrill': -1,
    'boring': -1,
    'boring song': -1,
    'boring melody': -1,
    'repetitive': -1,
    'repetitive song': -1,
    'repetitive melody': -1,
    'generic': -1,
    'generic beat': -1,
    'generic melody': -1,
    'unoriginal': -1,
    'copy': -1,
    'rip off': -1,
    'ripped off': -1,
    'lazy': -1,
    'sloppy': -1,
    'sloppy performance': -1,
    'sloppy mixing': -1,
    'messy': -1,
    'messy mix': -1,
    'messy arrangement': -1,
    'clashing': -1,
    'clashing instruments': -1,
    'clashing vocals': -1,
    'clash': -1,
    'noise': -1,
    'noisy': -1,
    'static': -1,
    'static sound': -1,
    'crackling': -1,
    'crackling sound': -1,
    'buzzing': -1,
    'buzzing sound': -1,
    'hum': -1,
    'beeping': -1,
    'feedback': -1,
    'squeaky': -1,
    'squeaky vocals': -1,
    'thin': -1,
    'thin vocals': -1,
    'thin sound': -1,
    'hollow': -1,
    'hollow vocals': -1,
    'hollow sound': -1,
    'metallic': -1,
    'robotic': -1,
    'unnatural': -1,
    'forced': -1,
    'forced vocals': -1,
    'fake': -1,
    'insincere': -1,
}

EN_SENTIMENT_WORDS = {**EN_POSITIVE_WORDS, **EN_NEGATIVE_WORDS}

# ===========================
# VIETNAMESE MODIFIERS/INTENSIFIERS
# ===========================

VI_MODIFIERS = {
    # Intensifiers (tăng cường)
    'rất': 2.0,              # very
    'cực': 2.0,              # extremely
    'cực kỳ': 2.0,           # extremely
    'cực thể': 2.0,          # extremely
    'quá': 2.0,              # too/so
    'quá mức': 2.0,          # excessively
    'vô cùng': 2.0,          # extremely
    'vô tận': 2.0,           # infinitely
    'tột cùng': 2.0,         # utmost
    'tuyệt': 1.5,            # extremely
    'tuyệt cùng': 1.5,       # extremely
    'tuyệt vời': 1.5,        # wonderfully
    'rùng': 1.5,             # very
    'nhiều': 1.2,            # lots
    'lắm': 1.5,              # a lot
    'lắm lắm': 1.5,          # a lot a lot
    'đặc biệt': 1.3,         # especially/particularly
    'đặc biệt là': 1.3,      # particularly
    'nhất': 1.5,             # very
    'nhất là': 1.5,          # especially
    'khôn xiết': 1.8,        # terribly/greatly
    'khôn': 1.8,             # terribly
    
    # Weakeners/Softeners (làm mềm)
    'hơi': 0.5,              # a bit/slightly
    'hơi hơi': 0.5,          # a little bit
    'một chút': 0.5,         # a little
    'một ít': 0.5,           # a little
    'có chút': 0.5,          # a bit
    'tạm': 0.5,              # somewhat
    'tạm tạm': 0.5,          # somewhat
    'bớt': 0.5,              # less
    'ít': 0.5,               # less
    'ít nhiều': 0.5,         # somewhat
    'không': 0.0,            # not (negation)
    'không phải': 0.0,       # not
    'chẳng': 0.0,            # not
    'chả': 0.0,              # not
    'gần': 0.8,              # almost/nearly
    'gần như': 0.8,          # almost
    'gần kề': 0.8,           # nearly
    'à là': 0.5,             # somewhat
    'cũng': 0.7,             # also/quite
    'cũng cảm': 0.7,         # somewhat feel
    'thường': 0.6,           # usually/fairly
    'thường thường': 0.6,    # usually
    'chút': 0.5,             # a bit
    'đôi khi': 0.6,          # sometimes
    'có khi': 0.6,           # sometimes
    'lần lữa': 0.6,          # sometimes
    'khi': 0.6,              # when/sometimes
    'tuy': 0.6,              # although
    'mặc dù': 0.6,           # although
}

# ===========================
# ENGLISH MODIFIERS/INTENSIFIERS
# ===========================

EN_MODIFIERS = {
    # Intensifiers
    'very': 2.0,
    'extremely': 2.0,
    'so': 2.0,
    'too': 2.0,
    'absolutely': 2.0,
    'completely': 2.0,
    'totally': 2.0,
    'utterly': 2.0,
    'incredibly': 2.0,
    'awfully': 2.0,
    'terribly': 2.0,
    'tremendously': 2.0,
    'immensely': 2.0,
    'enormously': 2.0,
    'vastly': 2.0,
    'hugely': 2.0,
    'remarkably': 2.0,
    'notably': 2.0,
    'particularly': 1.3,
    'especially': 1.3,
    'certainly': 1.5,
    'definitely': 1.5,
    'really': 1.5,
    'genuinely': 1.5,
    'truly': 1.5,
    'quite': 1.5,
    'rather': 1.5,
    'fairly': 1.5,
    'reasonably': 1.5,
    'pretty': 1.5,
    'most': 1.5,
    
    # Weakeners/Softeners
    'slightly': 0.5,
    'somewhat': 0.5,
    'fairly': 0.5,
    'rather': 0.5,
    'quite': 0.5,
    'a bit': 0.5,
    'a little': 0.5,
    'a little bit': 0.5,
    'barely': 0.5,
    'hardly': 0.5,
    'scarcely': 0.5,
    'almost': 0.8,
    'nearly': 0.8,
    'largely': 0.8,
    'mostly': 0.8,
    'generally': 0.8,
    'usually': 0.8,
    'often': 0.8,
    'sometimes': 0.6,
    'occasionally': 0.6,
    'perhaps': 0.6,
    'possibly': 0.6,
    'arguably': 0.6,
    'sort of': 0.5,
    'kind of': 0.5,
    'in a way': 0.5,
    'not': 0.0,
    'no': 0.0,
    'never': 0.0,
}
